### ISSUE TITLE
Поискать библиотеки или сторонние аддоны (или что-то такое) для "разумных" противников

### ISSUE THREAD

**Issue by NivorBUD** [NivorBUDTeam/VMINT#14]

**Comment by Onnya** [comment]
Поискал в Unity asset store, бесплатных вариантов не нашел. Поискал гайды в интернете, вроде бы самая сложная часть системы реализована в самом Unity, так что написать нужно будет не так много: видимость, патрулирование и преследование. Так что в вопросе противников ответ - пишу сам.
